# .streamlit/secrets.toml
firestore_credentials ="""
{
  "type": "service_account",
  "project_id": "my-project-retail-data",
  "private_key_id": "59493b0ca2d4219ee8ddb4704bc46588d92ac888",
  "private_key": "-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCWEuSIBajrSDm8
2NWQE8NboLkvcSd69OQ+nN8rlsmhQZzNrISwHKv9YVf1RLegf5Zcn/sHk6cagQWD
taQwjzzfMrJ67iGZWWs7+ggonz5QS6mhmPXBmGJnTxgihJ3O1MsNlpFOdrzPnoVo
KmiXxXxMfDY8wqWi8MqPO3aNm+0jueXaHDFyP2VMCkG1gbWO2inegfcFJjJ6VPPg
PL1cfOaSpBivJbrZCdqJDFQDzXyUPSdgFZRUqml7MBUECiEdJgn1EWNgUMcbYuv9
YFWtXwC/a91Ad8uGr2Xd7sjZqH2kyYLu+pva6I/ykZKU2zHQV5Ts9XYX4qaXqgsb
9UpJTGahAgMBAAECggEAFE6SJeW+KbgoN+mPXGOQN8HTRrueoACrMd3ARQGuXuel
9B64BaybiTm20TVvM4SQMBBlw2yzW97BhET75qY7MmiFxiSa30k+x/rZR8XkhLD4
TymHd57LEfed6G3RfL9GipwpJVjjy6RDoQi8Bm1umFrma+pax2WVwzPkotzKhd7Y
rrOUSLifg3u+Iksm5RToaouqNSzypBqdI0ilblf7mX4SSGX5oXYdGpI+y5rLVF4i
noRrFtXJNMRe4dktyvarZMMdlvECjXpwynad8RRIaNrkmtRQ3PedWg2zrJKGOuv4A
+a8It58i58V08XhwCRk4Q7+jy9wEX1WiRWfMPxmuwQKBgQDI9IiahZ66ZChRQV4N
z7BPl9cEan96vuretKhgWAX0+9LlzPKosju71mMBXiJlWJWxj4ZV5hlyUZqvakAI
k/ffYvcvBWPQGBgUStIh/N3fou8AQH+gGCgws1YQ3HtVa/1GpiW0CBSsvBAqZ16o
CL4ROPFZ1mBv5ysGICj36SFPPQKBgQC/Lm5p4b9Cv1+kEX1XmlV1I4/n10xPFa1A
TT7k10ZGL+JLhe4w/6rxTEHSMIjTl0vODob21VXiKgTltzy6oBz+eK6DO3LsLiUM
TIiajvMBN6RQLQjJzBnYIdZOZ0Y7mu1gb6E4dhvA1X/FDDDcaa9qJ/O6ARS9dpZM
X2PjUvLrNQKBgBl3K4xxXGEAaj+JyhJz/ELJ2hycJlV2tirMt/2lifO2qc4nP6Tz
GTC/hUJaHH+9TxL2Pi7KfvUGtFSAYWb04Vd0oiBaTYDEXODNbn2SHsfFTQY6JjIy
nfX1WbJSsbBCyI6F9Uo/S6lPNbTsCaHNg0D08exFIYmYr5D7denOYHnl9AoGBAIKc
0CZaanbJlCfdIwsEj7nVr+0utB2bq5+wpnVldcdh03LRb2feZAUymg1lxzT3unxu
hFqCaYh4OJxQUZcW6HgaLu/NX7hn1jvO1czyOKbuQr3b5pMnc8irZWRvPhZexCoM
WdLfLhrSQdZ3e7I6KfOWk/bR4j+GkyxeRzn5Y6i5AoGBAMMSvJwxTuunDddhdWsn
PEODAFFwCWolHZfeZbKMSWST8MB79BtIxAwZG5QAOYcADtJhLl0wMvxX8tVGXT7y
RHkv0RaMxb+ea05jqc+XPlkfcdxQB+/+RtW0+IwNpfV0uyTZgt7gGRGKLYDgRjYP
no8hWo/h8cHGa2vH9zsv8KpX7
-----END PRIVATE KEY-----
"""
  "client_email": "streamlit-firestore-admin@my-project-retail-data.iam.gserviceaccount.com",
  "client_id": "116881081607233972244",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-firestore-admin%40my-project-retail-data.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
**Perubahan penting:** Di dalam string `private_key`, saya telah menghapus semua `\n` dan menggantinya dengan baris baru yang sebenarnya. Saat Anda menggunakan tiga tanda kutip (`"""`) untuk string multiline di TOML, karakter baris baru yang sebenarnya akan dipertahankan.

Untuk kode Python Anda, saya telah menambahkan baris debug tambahan untuk mencetak panjang `private_key` setelah `strip()`. Ini dapat membantu memverifikasi bahwa string tersebut memiliki panjang yang diharapkan dan tidak ada karakter tersembunyi yang menyebabkan masalah.

Berikut adalah kode Python yang telah diperbarui untuk Canvas "Streamlit Business Dashboard App" Anda:


http://googleusercontent.com/immersive_entry_chip/0
