# .streamlit/secrets.toml
firestore_credentials = """
{
  "type": "service_account",
  "project_id": "my-project-retail-data",
  "private_key_id": "0381115efc9937cd2521399111800ab79347c7afc",
  "private_key": "-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC11x51EbeZSV4e
wJgO/eYO7CCyCsddY1+poWa5CkDuFvgV7wogOeOikRNqAbmX0i4nl49skfmZH0Dy
zi4n5yR7bfCOZHE+Vwf4bLUFFKK1iGfAcbq3mKspAnE2rCZhxuqa4QE0OF0SzjTS
lfSpuLeDg35I0zFgX48MfDpGV9W1S276lP7Em6OksRYPDiAwESOIhMgy/gtV7Kx3
lbmUyXNNi9hsdw2Y3slbgQZ0QBU48ecdtgLTpl0L6+iwhorWZ0K/ejXLRVlir002
vny582Wg3HHnnTrVDSAVotmkhYmkdWexlpka1rOHdc7AGq+1Oi/wqUctdk4g3EL1
KXcHgzQtAgMBAAECggEAB9xJu8PNTPoH8IpgyF0fYcvBShD/N0FBdGK/vwb7cY9a
oBAaPvRhq7hbv3xdmnuCdUGu+IGC6aSZOSXChwUN5awF9xHOd2RpuspwNM0Ej5Za
7c28xYz68SXi4PsmGZnwsEtDsw8wrsxtKiFDV0bd3/iCMAG5I7Jdy6tfFYVcfp62
fGX8/mrbqfnB/h9kUkHaqYyX4jlFGcaN+esHb1CQATRNYH5c9Fo3MqBwTlHwc7VL
n/ZnFdpHONRsWdIIQlzsczSuYdIrgznPfHbNH/WF1KKC5ftRD5uvsSI3GQUpEGWy
H01XBQoVtxRUTHArN1ovLWOhpxK8yo5GYxYbkm1YAQKBgQDhj1OD5NLj7vELWFCI
UoxdmwMdzmVEHchGrsPQlvJnFHp8p6hEl7LihhVfeIjaJGWEfVNqBJnSFliH0ISk
CvGklCDcs5byIXxsn2u/9ZRv5nDpL6lfQH300Lb+DicoRy7BNdXvgFBqhAZl3Uq3
m6VeI8F/608GjQ1LPhPEa2r6LQKBgQDOYV0BY4wyqt5RBwoALTQV9BR3oArJp66V
/vJ/3h9mbUUstTLG87EjZDpR4fCh2wJ12cN2W3DuFA9uaFTZHTjR75tZxSEiiuf9
7ziRr3A9AsU3hwvj/azH+dZrsi1lSjsgkJW18vslwbyi66AysuRhycKLduP4krfW
+I27PH9iAQKBgQCzMInIXiCrs0cLHD3eDrY0JtFy/GS2mHJitLQbIc+w1DP6k7a5
x0n1a0/PaJJPulprxqRdtQn+PIJYYu784zTU6liw/HsOIEwYfw26kf46Z3eLyLFl
Wna15pl5ewTgmqwqEfrDKcy40enDQun4s03MW9t9JBLDwYquG8LYZ/20gQKBgCu
OnYI+SBfme6rWxTvRzokmnU49EyHJ191U9Enb770eqUedC5U1WAi77dobyT1j24J
nTfj8j3/MDfVlEQEodcoFOZHd/FTX04q8ztrj6scHSrJyCTlZlUvrWxjQvJAkZcF6
4XTyMRojKuZ0aBVLF8lEYM8zbABTVpGLEzSb8BveAQKBgHZNjciS6+Jo5UP5/VFR
/YUqZRM/+FbIDdgfioFC/KUq6TSje4Ij3HWnVzGZ//Oi1CCFGyH0Ril7UXh7/hyX
ndUOmFAgiBBPrBaEMALO3R7aSrVaaA6LBmjcuWtJ43wtyJXeYhxEZHUZ5jqt4Ehnt
6G9AQmemuBpY3eX7vGn/BwO9
-----END PRIVATE KEY-----",
  "client_email": "streamlit-firestore-admin@my-project-retail-data.iam.gserviceaccount.com",
  "client_id": "116881081607233972244",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-firestore-admin%40my-project-retail-data.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
