# .streamlit/secrets.toml

[firebase]
type = "service_account"
project_id = "my-project-retail-data"
private_key_id = "59493b0ca2d4219ee8ddb4704bc46588d92ac888"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCWEuSIBajrSDm8
2NWQE8NboLkvcSd69OQ+nN8rlsmhQZzNrISwHKv9YVf1RLegf5Zcn/sHk6cagQWD
taQwjzzfMrJ67iGZWW87+ggonz5QS6mhmPXBmGJnTxgihJ3O1MsNlpFOdrzPnoVo
KmiXxXxMfDY8wqWi8MqPO3aNm+0jueXaHDFyP2VMCkG1gbWO2inegfcFJjJ6VPPg
PL1cfOaSpBivJbrZCdqJDFQDzXyUPSdgFZRUqml7MBUECiEdJgn1EWNgUMcbYuv9
YFWtXwC/a91Ad8uGr2Xd7sjZqH2kyYLu+pva6I/ykZKU2zHQV5Ts9XYX4qaXqgsb
9UpJTGahAgMBAAECggEAFE6SJeW+KbgoN+mPXGOQN8HTzRueoACrMd3ARQGuXuel
9B64BaybiTm20TVvM4SQMBBlw2yzW97BhET75qY7MmiFxiSa30k+x/rZR8XkhLD4
TymHd57LEfed6G3RfL9GipwpJVjjy6RDoQi8Bm1umFrma+pax2WVwzPkotzKhd7Y
r4OUSLifg3u+Iksm5RToaouqNSzypBqdI0ilblf7mX4SSGX5oXYdGpI+y5rLVF4i
oRrFtXJNMRe4dktyvarZMMdlvECjXpwynad8RRIaNrkmtRQ3PedWg2zrJKGOuv4A
+a8It58i58V08XhwCRk4Q7+jy9wEX1WiRWfMPxmuwQKBgQDI9IiahZ66ZChRQV4N
-----END PRIVATE KEY-----"""
client_email = "streamlit-firestore-admin@my-project-retail-data.iam.gserviceaccount.com"
client_id = "116881081607233972244"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-firestore-admin%40my-project-retail-data.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
